# Generated by Django 2.2 on 2019-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokemons',
            field=models.ManyToManyField(blank=True, through='trainers.PokemonOwnership', to='trainers.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
    ]
