# Generated by Django 2.2 on 2019-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_auto_20190427_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(blank=True, upload_to='trainer_photos'),
        ),
    ]
