# Generated by Django 2.2 on 2019-04-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_auto_20190427_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_photo',
            new_name='photo',
        ),
    ]
