# Generated by Django 2.2 on 2019-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0011_auto_20190428_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='trainer_photos'),
        ),
    ]
