# Generated by Django 2.2 on 2019-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_auto_20190428_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
