# Generated by Django 2.2 on 2019-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_auto_20190429_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(null=True, upload_to='pokemon_photos'),
        ),
    ]
