# Generated by Django 2.2 on 2019-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_pokemon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank=True, choices=[('BUG', 'BUG'), ('DARK', 'DARK'), ('DRAGON', 'DRAGON'), ('ELECTRIC', 'ELECTRIC'), ('FAIRY', 'FAIRY'), ('FIGHTING', 'FIGHTING'), ('FIRE', 'FIRE'), ('FLYING', 'FLYING'), ('GHOST', 'GHOST'), ('GRASS', 'GRASS'), ('GROUND', 'GROUND'), ('ICE', 'ICE'), ('NORMAL', 'NORMAL'), ('POISON', 'POISON'), ('PSYCHIC', 'PSYCHIC'), ('ROCK', 'ROCK'), ('STEEL', 'STEEL'), ('WATER', 'WATER'), ('???', '???')], max_length=10),
        ),
    ]
