# Generated by Django 2.2 on 2019-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_auto_20190429_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
