# Generated by Django 2.2 on 2019-05-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0016_pokemon_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='nickname',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.Pokemon'), max_length=32),
        ),
    ]
