# Generated by Django 2.2 on 2019-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0018_auto_20190501_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
    ]
