# Generated by Django 2.2 on 2019-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0021_auto_20190501_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='shiny',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
    ]
