# Generated by Django 2.2 on 2019-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0023_auto_20190501_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='nickname',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.ForeignKey>', max_length=32),
        ),
    ]
