# Generated by Django 2.2 on 2019-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0024_auto_20190501_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='nickname',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
