# Generated by Django 2.2 on 2019-05-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0025_auto_20190501_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonownership',
            name='pokemon',
            field=models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.CASCADE, to='trainers.Pokemon'),
        ),
    ]
